-- MySQL Script generated by MySQL Workbench
-- Wed Jun 18 00:02:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema demm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `demm` ;

-- -----------------------------------------------------
-- Schema demm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demm` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `demm` ;

-- -----------------------------------------------------
-- Table `demm`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demm`.`room` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demm`.`room` (
  `id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `category` VARCHAR(150) NOT NULL,
  `floor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demm`.`guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demm`.`guests` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demm`.`guests` (
  `id` INT NOT NULL,
  `fullname` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demm`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demm`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demm`.`users` (
  `id` INT NOT NULL,
  `fullname` VARCHAR(100) NOT NULL,
  `position` ENUM('Администратор', 'Директор', 'Клиент') NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `ban` INT NOT NULL DEFAULT 3,
  `auth` INT NOT NULL DEFAULT 0,
  `lasrlogin` DATETIME NULL,
  `status` ENUM('Заблокирован', 'Активен') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demm`.`guests_currently_living_in_the_hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demm`.`guests_currently_living_in_the_hotel` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demm`.`guests_currently_living_in_the_hotel` (
  `number` INT NOT NULL,
  `category` VARCHAR(200) NOT NULL,
  `guests` VARCHAR(100) NOT NULL,
  `entry` DATE NOT NULL,
  `exit` DATE NULL,
  `guests_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`number`, `guests_id`, `room_id`),
  CONSTRAINT `fk_guests_currently_living_in_the_hotel_guests`
    FOREIGN KEY (`guests_id`)
    REFERENCES `demm`.`guests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_guests_currently_living_in_the_hotel_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `demm`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_guests_currently_living_in_the_hotel_guests_idx` ON `demm`.`guests_currently_living_in_the_hotel` (`guests_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_guests_currently_living_in_the_hotel_room1_idx` ON `demm`.`guests_currently_living_in_the_hotel` (`room_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demm`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demm`.`report` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demm`.`report` (
  `number` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `date_exit` DATE NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`number`, `room_id`),
  CONSTRAINT `fk_report_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `demm`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_report_room1_idx` ON `demm`.`report` (`room_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
